### ISSUE TITLE
Article Protoclle de selection 

### ISSUE THREAD

**Issue by nprime496** [ENSP-AI-Mentoring/pick_some_members#4]
Hi @1001pepi 
blabla selectionné article dispo ?

**Comment by nprime496** [comment]
l'article 2024-01-18

**Comment by 1001pepi** [comment]
Ouais dispo...

**Comment by nprime496** [comment]
lien vers le google docs

**Comment by nprime496** [comment]
super merci, on va publier.
on te tien au courant.
